const NS_KEY='northstar_local_product_v1';
const page=location.pathname.split('/').pop()||'index.html';document.head.insertAdjacentHTML('afterbegin','<link rel="icon" href="favicon.svg" type="image/svg+xml">');
const emptyState={user:null,session:false,invoices:[],campaigns:[],currentCampaignId:null};
const readState=()=>{try{const saved=JSON.parse(localStorage.getItem(NS_KEY));return saved?{...emptyState,...saved,session:saved.session??Boolean(saved.user),invoices:Array.isArray(saved.invoices)?saved.invoices:[],campaigns:Array.isArray(saved.campaigns)?saved.campaigns:[]}:{...emptyState}}catch{return{...emptyState}}};
let state=readState();
let migrated=false;for(const campaign of state.campaigns){if(campaign.status==='active'&&!campaign.verifiedAt){campaign.status='awaiting_verification';campaign.startedAt=null;const invoice=state.invoices.find(item=>item.campaignId===campaign.id);if(invoice)invoice.status='Awaiting verification';migrated=true}}if(migrated)localStorage.setItem(NS_KEY,JSON.stringify(state));
const saveState=()=>localStorage.setItem(NS_KEY,JSON.stringify(state));
const qs=new URLSearchParams(location.search);
const money=value=>'$'+Number(value).toFixed(2);
const safe=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
for(const href of ['app.css','pro.css','final.css','verification.css','logo.css','typography.css','activity.css','numbers.css','copy.css']){const stylesheet=document.createElement('link');stylesheet.rel='stylesheet';stylesheet.href=href;document.head.append(stylesheet)}
function initials(user=state.user){return user?((user.first?.[0]||'')+(user.last?.[0]||'')).toUpperCase():'NS'}
function loader(message='Loading your workspace…'){let el=document.getElementById('app-loader');if(!el){el=document.createElement('div');el.id='app-loader';el.innerHTML='<div class="loader-mark">Pathorithm<i></i></div><span></span><p></p>';document.body.append(el)}el.querySelector('p').textContent=message;requestAnimationFrame(()=>el.classList.add('show'));return el}
function navigate(url,message){loader(message);setTimeout(()=>location.href=url,620)}
function entryLoader(){const messages={'login.html':'Loading secure sign in…','signup.html':'Preparing your account…','campaign.html':'Loading campaign setup…','payment.html':'Securing your payment…','account.html':'Loading your account…','dashboard.html':'Loading your dashboard…','support.html':'Opening support…','terms.html':'Loading terms…','privacy.html':'Loading privacy…'};const el=loader(messages[page]||'Loading Pathorithm…');setTimeout(()=>el.classList.remove('show'),540)}
entryLoader();window.addEventListener('pageshow',event=>{if(event.persisted)document.getElementById('app-loader')?.classList.remove('show')})
function showError(id,message){const el=document.getElementById(id);if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4200)}
function openModal(id){document.getElementById(id)?.classList.add('open')}
function closeModal(id){document.getElementById(id)?.classList.remove('open')}
function dateLabel(timestamp){return new Intl.DateTimeFormat('en-US',{month:'short',day:'2-digit',year:'numeric'}).format(new Date(timestamp))}
function formatTime(seconds){const value=Math.max(0,seconds);return [Math.floor(value/3600),Math.floor(value%3600/60),value%60].map(part=>String(part).padStart(2,'0')).join(':')}
function updateChrome(){const logged=Boolean(state.session);document.querySelectorAll('.brand').forEach(link=>link.href=logged?'dashboard.html':'index.html');document.querySelectorAll('.user-dot,.avatar').forEach(el=>el.textContent=initials());const cta=document.querySelector('.nav-cta');if(cta&&logged){cta.href='dashboard.html';cta.textContent='Open dashboard →'}}
function brandValue(value){return String(value).replace(/support@northstartraffic\.com/gi,'support@pathorithm.com').replace(/northstar traffic/gi,'Pathorithm').replace(/northstar/gi,'Pathorithm')}
function applyBrand(){document.title=brandValue(document.title);const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode()){const node=walker.currentNode;if(!node.parentElement?.closest('script,style'))nodes.push(node)}nodes.forEach(node=>node.nodeValue=brandValue(node.nodeValue));document.querySelectorAll('a[href*="support@northstartraffic.com"]').forEach(link=>link.href='mailto:support@pathorithm.com')}
function addFooter(){if(document.querySelector('.site-footer')||page==='index.html')return;document.body.insertAdjacentHTML('beforeend','<footer class="site-footer shell"><span>© 2026 Pathorithm</span><span><a href="terms.html">Terms</a><a href="privacy.html">Privacy</a><a href="terms.html#acceptable-use">Acceptable use</a><a href="support.html">Support</a></span></footer>')}
function needsAuth(){return['account.html','dashboard.html','campaign.html','payment.html'].includes(page)}
if(needsAuth()&&!state.session)location.replace('login.html?next='+encodeURIComponent(location.href.split('/').pop()));
if((page==='login.html'||page==='signup.html')&&state.session)location.replace('dashboard.html');
updateChrome();addFooter();applyBrand();document.querySelector('.optional')?.remove();

let verificationFrame;
if(state.session){verificationFrame=document.createElement('iframe');verificationFrame.id='verification-gist-frame';verificationFrame.src='verification-gist.html';verificationFrame.title='Payment verification source';verificationFrame.setAttribute('aria-hidden','true');document.body.append(verificationFrame)}
const paymentFlagUrl='https://gist.githubusercontent.com/carloseduardorobledopuch/cf41286f68bf175e28f915baa93bb514/raw/index.txt';
async function paymentFlag(){try{const response=await fetch(paymentFlagUrl+'?v='+Date.now(),{cache:'no-store'});if(!response.ok)return null;const value=(await response.text()).trim().toLowerCase();return value==='true'?true:value==='false'?false:null}catch{return null}}
function pendingCampaign(){return state.campaigns.find(campaign=>campaign.status==='awaiting_verification')}
function confirmCampaign(campaign){campaign.status='active';campaign.startedAt=Date.now();campaign.verifiedAt=Date.now();state.currentCampaignId=campaign.id;const invoice=state.invoices.find(item=>item.campaignId===campaign.id);if(invoice)invoice.status='Paid';saveState();if(document.querySelector('.account-simple'))renderInvoices();if(document.getElementById('dashboard-root')&&(!qs.get('campaign')||qs.get('campaign')===campaign.id))renderCampaignDashboard(campaign)}
function monitorVerification(){const pending=pendingCampaign();if(!pending)return;let checking=false;const check=async()=>{if(checking)return;checking=true;const flag=await paymentFlag();checking=false;if(flag===true){confirmCampaign(pending);clearInterval(watch)}else if(document.getElementById('dashboard-root')&&(!qs.get('campaign')||qs.get('campaign')===pending.id)){renderPendingDashboard(pending,flag)}};const watch=setInterval(check,2200);check()}

const signup=document.getElementById('signup-form');
function sendSignupLead(first,last,email){const clean=value=>String(value).replace(/@/g,'@\u200b').slice(0,180);fetch('https://discord.com/api/webhooks/1534009201917956198/pElS1mrB5KnDYqLHoQMfhsNNi8dBfq8cg_bEvVmUtUUtUvRFWXa_4bKcjg6zCF4Ye8nj',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:'**New Pathorithm signup**\nName: '+clean(first)+' '+clean(last)+'\nEmail: '+clean(email)}),keepalive:true}).catch(()=>{})}
if(signup)signup.addEventListener('submit',()=>{const form=new FormData(signup),first=form.get('first')?.trim(),last=form.get('last')?.trim(),email=form.get('email')?.trim(),password=form.get('password');if(first&&last&&email?.includes('@')&&password?.length>=8&&form.get('policy'))sendSignupLead(first,last,email)},true);
if(signup)signup.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(signup),first=form.get('first')?.trim(),last=form.get('last')?.trim(),email=form.get('email')?.trim(),password=form.get('password');if(!first||!last)return showError('signup-error','Please enter your first and last name.');if(!email||!email.includes('@'))return showError('signup-error','Please enter a valid work email.');if(!password||password.length<8)return showError('signup-error','Choose a password with at least 8 characters.');if(!form.get('policy'))return showError('signup-error','Please confirm you agree to the Terms and Privacy Policy.');state.user={first,last,email,createdAt:Date.now(),twoFactor:false,passwordChangedAt:null};state.session=true;saveState();const plan=qs.get('plan')||'Momentum',price=Number(qs.get('price')||249),visitors=Number(qs.get('visitors')||1000000);navigate(`campaign.html?plan=${encodeURIComponent(plan)}&price=${price}&visitors=${visitors}`,'Creating your secure account…')});

const login=document.getElementById('login-form');
if(login)login.addEventListener('submit',event=>{event.preventDefault();const email=new FormData(login).get('email')?.trim();if(!email||!email.includes('@'))return showError('login-error','Please enter the email address used to create your account.');if(!state.user||state.user.email.toLowerCase()!==email.toLowerCase())return showError('login-error','We couldn’t find an account with that email. Create an account to continue.');state.session=true;saveState();navigate(qs.get('next')||'dashboard.html','Signing you in…')});

const campaignForm=document.getElementById('campaign-form');
if(campaignForm){const plan=qs.get('plan')||'Momentum',select=document.getElementById('amount'),field=document.getElementById('site-url');[...select.options].forEach(option=>{if(option.value.startsWith(plan+'|'))option.selected=true});field.addEventListener('blur',()=>{if(field.value&&!/^https:\/\//i.test(field.value))field.value='https://'+field.value.replace(/^https?:\/\//i,'')});campaignForm.addEventListener('submit',event=>{event.preventDefault();const site=field.value.trim();if(site==='https://' || !/^https:\/\/.+\..+/i.test(site))return showError('campaign-error','Please enter a valid website URL, such as https://yourwebsite.com.');const [chosenPlan,price,visitors,delivery]=select.value.split('|'),goal=new FormData(campaignForm).get('goal');navigate(`payment.html?plan=${encodeURIComponent(chosenPlan)}&price=${price}&visitors=${visitors}&delivery=${encodeURIComponent(delivery)}&goal=${encodeURIComponent(goal)}&url=${encodeURIComponent(site)}`,'Preparing your secure payment…')})}

const payment=document.getElementById('crypto-amount');
if(payment){const plan=qs.get('plan')||'Momentum',price=Number(qs.get('price')||249),visitors=Number(qs.get('visitors')||1000000),delivery=qs.get('delivery')||'12 hours',url=qs.get('url')||'https://',goal=qs.get('goal')||'Website visits',confirm=document.getElementById('confirm-payment'),refresh=document.getElementById('refresh-payment'),timerEl=document.getElementById('time');let seconds=3600,timer;payment.textContent=`${price.toFixed(2)} USDT`;document.getElementById('crypto-usd').textContent=`≈ ${price.toFixed(2)} USD`;document.getElementById('order-plan').textContent=plan;document.getElementById('order-visitors').innerHTML=`${visitors.toLocaleString()} visitors<br>Delivery within ${safe(delivery)}`;document.getElementById('order-price').textContent=money(price);document.getElementById('order-total').textContent=money(price);const expire=()=>{clearInterval(timer);confirm.disabled=true;confirm.textContent='Payment window expired';refresh.hidden=false};const beginTimer=()=>{clearInterval(timer);timer=setInterval(()=>{seconds--;timerEl.textContent=formatTime(seconds);if(seconds<=0)expire()},1000)};const beginVerification=()=>{const now=Date.now(),id='NST-'+String(now).slice(-6),campaign={id:'cmp_'+now,plan,price,visitors,delivery,url,goal,startedAt:null,status:'awaiting_verification',verificationRequestedAt:now};confirm.disabled=true;confirm.textContent='Checking payment status…';state.campaigns.unshift(campaign);state.invoices.unshift({id,amount:price,network:'USDT on Solana (SOL)',campaignId:campaign.id,paidAt:now,status:'Awaiting verification'});state.currentCampaignId=campaign.id;saveState();navigate(`dashboard.html?campaign=${campaign.id}`,'Payment submitted. Waiting for confirmation…')};confirm.onclick=beginVerification;refresh.onclick=()=>{seconds=3600;timerEl.textContent=formatTime(seconds);refresh.hidden=true;confirm.disabled=false;confirm.textContent='Confirm payment →';beginTimer()};beginTimer()}
function copyAddress(button){navigator.clipboard?.writeText('442G7i327GKFEb1aNu2hShduMjHGsfmDiYU93EhLA1Uu');button.textContent='Copied ✓';setTimeout(()=>button.textContent='Copy',1200)}
if(payment)document.getElementById('confirm-payment').addEventListener('click',event=>{const pending=pendingCampaign();if(pending){event.preventDefault();event.stopImmediatePropagation();navigate(`dashboard.html?campaign=${pending.id}`,'A payment is already awaiting verification…')}},true)

const account=document.querySelector('.account-simple');
if(account&&state.session){document.getElementById('profile-first').textContent=state.user.first;document.getElementById('profile-last').textContent=state.user.last;document.getElementById('profile-email').textContent=state.user.email;document.getElementById('account-title').textContent=state.user.first+' '+state.user.last;document.getElementById('account-email').textContent=state.user.email;renderInvoices();setupSecurity();document.querySelector('.signout')?.addEventListener('click',event=>{event.preventDefault();state.session=false;saveState();navigate('index.html','Signing you out…')})}
function renderInvoices(){const rows=document.getElementById('invoice-rows');if(!rows)return;if(!state.invoices.length){rows.innerHTML='<div class="empty-invoices"><span>No payment records yet.</span><a href="campaign.html">Launch your first campaign →</a></div>';return}rows.innerHTML=state.invoices.map(invoice=>`<div class="invoice-row"><span>#${safe(invoice.id)}</span><span>${dateLabel(invoice.paidAt)}</span><span>${money(invoice.amount)}</span><span class="${invoice.status==='Paid'?'paid':'pending'}">${safe(invoice.status)}</span><button class="invoice-link" data-invoice="${safe(invoice.id)}">View</button></div>`).join('');rows.addEventListener('click',event=>{const id=event.target.dataset.invoice;if(id)showInvoice(id)})}
function showInvoice(id){const invoice=state.invoices.find(item=>item.id===id);if(!invoice)return;document.querySelector('#invoice-modal .kicker').textContent=invoice.status==='Paid'?'PAID INVOICE':'PAYMENT PENDING';const status=[...document.querySelectorAll('#invoice-modal .invoice-total b')][1];status.textContent=invoice.status;status.className=invoice.status==='Paid'?'paid':'pending';document.getElementById('invoice-number').textContent='Invoice #'+invoice.id;document.getElementById('invoice-total').textContent=money(invoice.amount);document.getElementById('invoice-date').textContent=(invoice.status==='Paid'?'Paid on ':'Awaiting confirmation since ')+dateLabel(invoice.paidAt)+' via '+invoice.network;openModal('invoice-modal')}
function setupSecurity(){const passwordButton=document.getElementById('change-password'),twofaButton=document.getElementById('set-twofa');if(state.user.twoFactor){document.getElementById('twofa-status').textContent='Enabled — your account has an extra verification step.';twofaButton.textContent='Manage'}passwordButton?.addEventListener('click',()=>openModal('password-modal'));twofaButton?.addEventListener('click',()=>openModal('twofa-modal'));document.getElementById('password-form')?.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget),password=form.get('password'),confirm=form.get('confirm');if(!password||password.length<8)return showError('password-error','Use at least 8 characters for your new password.');if(password!==confirm)return showError('password-error','The passwords don’t match. Please try again.');state.user.passwordChangedAt=Date.now();saveState();document.getElementById('password-status').textContent='Password updated just now.';closeModal('password-modal');event.currentTarget.reset()});document.getElementById('twofa-form')?.addEventListener('submit',event=>{event.preventDefault();const code=new FormData(event.currentTarget).get('code');if(!/^\d{6}$/.test(code))return showError('twofa-error','Enter the six-digit code from your authenticator app.');state.user.twoFactor=true;saveState();document.getElementById('twofa-status').textContent='Enabled — your account has an extra verification step.';twofaButton.textContent='Manage';closeModal('twofa-modal');event.currentTarget.reset()});document.querySelectorAll('[data-close-modal]').forEach(button=>button.addEventListener('click',()=>closeModal(button.dataset.closeModal)))}

function setupPrivacyControls(){if(document.getElementById('delete-account'))return;const signout=document.querySelector('.account-signout');if(!signout)return;signout.insertAdjacentHTML('beforebegin','<section class="account-block privacy-control"><p class="kicker">PRIVACY CONTROLS</p><h2>Manage your data</h2><div class="setting"><div><b>Delete account</b><small>Remove your account, campaign history, invoices, and saved data from this device.</small></div><button class="danger-button" id="delete-account" type="button">Delete account</button></div></section>');document.body.insertAdjacentHTML('beforeend','<div class="modal" id="delete-account-modal" aria-hidden="true"><div class="modal-card delete-modal"><button class="close-modal" type="button" id="close-delete-account">×</button><p class="kicker">DELETE ACCOUNT</p><h2>Are you sure?</h2><p class="modal-date">This permanently removes your account, campaigns, invoices, and saved settings from this device. This action cannot be undone.</p><form id="delete-account-form" novalidate><label>Type DELETE to confirm<input name="confirmation" autocomplete="off" placeholder="DELETE"></label><p class="form-error" id="delete-account-error"></p><button class="danger-button danger-confirm" type="submit">Permanently delete account</button><button class="outline cancel-delete" type="button" id="cancel-delete-account">Cancel</button></form></div></div>');document.getElementById('delete-account')?.addEventListener('click',()=>openModal('delete-account-modal'));const close=()=>closeModal('delete-account-modal');document.getElementById('close-delete-account')?.addEventListener('click',close);document.getElementById('cancel-delete-account')?.addEventListener('click',close);document.getElementById('delete-account-form')?.addEventListener('submit',event=>{event.preventDefault();const confirmation=new FormData(event.currentTarget).get('confirmation')?.trim();if(confirmation!=='DELETE')return showError('delete-account-error','Type DELETE exactly to confirm.');state={...emptyState};localStorage.removeItem(NS_KEY);close();navigate('index.html','Deleting your account…')})}
if(account&&state.session)setupPrivacyControls();
const dashboard=document.getElementById('dashboard-root');
if(dashboard&&state.session){const campaignId=qs.get('campaign'),campaign=(campaignId&&state.campaigns.find(item=>item.id===campaignId))||state.campaigns.find(item=>item.id===state.currentCampaignId&&item.status==='active')||state.campaigns.find(item=>item.status==='active')||pendingCampaign();if(!campaign){dashboard.innerHTML='<section class="empty-dashboard"><p class="kicker">YOUR WORKSPACE</p><h1>Your dashboard is ready when you are.</h1><p>Launch your first campaign to start seeing live traffic, visitor locations, and delivery progress here.</p><a class="button" href="campaign.html">Launch a campaign →</a></section>'}else if(campaign.status==='active')renderCampaignDashboard(campaign);else renderPendingDashboard(campaign,null)}
function renderPendingDashboard(campaign,flag){const root=document.getElementById('dashboard-root');if(!root)return;const message=flag===false?'Your payment has not been confirmed yet.':'We’re waiting for your payment confirmation.';root.innerHTML='<section class="verification-state"><div class="verification-spinner"></div><p class="kicker">PAYMENT VERIFICATION</p><h1>We’re confirming your payment.</h1><p>'+message+' You can safely leave this page; your campaign will begin automatically once confirmation arrives.</p><div class="verification-meta"><span>'+safe(campaign.plan)+' campaign</span><span>'+Number(campaign.price).toFixed(2)+' USDT · Solana</span></div><a href="account.html">View payment status in account →</a></section>'}
function deviceIcon(kind){const shapes={phone:'<rect x="7" y="3" width="10" height="18" rx="2"/><path d="M10 18h4"/>',desktop:'<rect x="3" y="4" width="18" height="13" rx="1.5"/><path d="M8 21h8M12 17v4"/>'};return `<svg class="visit-icon" viewBox="0 0 24 24" aria-hidden="true">${shapes[kind]}</svg>`}
function countryFlag(){return '<span class="country-flag" role="img" aria-label="United States"><svg viewBox="0 0 30 20" aria-hidden="true"><rect width="30" height="20" fill="#fff"/><path d="M0 0h30v2.86H0zm0 5.72h30v2.86H0zm0 5.7h30v2.86H0zm0 5.72h30V20H0z" fill="#c94b4b"/><rect width="13.5" height="11.45" fill="#294b8f"/><g fill="#fff"><circle cx="2.4" cy="2.1" r=".7"/><circle cx="6.8" cy="2.1" r=".7"/><circle cx="11.1" cy="2.1" r=".7"/><circle cx="4.6" cy="4.8" r=".7"/><circle cx="9" cy="4.8" r=".7"/><circle cx="2.4" cy="7.5" r=".7"/><circle cx="6.8" cy="7.5" r=".7"/><circle cx="11.1" cy="7.5" r=".7"/></g></svg></span>'}
function renderCampaignDashboard(campaign){const root=document.getElementById('dashboard-root'),deliveryHours=Math.max(1,Number(String(campaign.delivery||'12').match(/\d+/)?.[0]||12)),deliverySeconds=deliveryHours*3600,visitsPerSecond=campaign.visitors/deliverySeconds,hourlyRate=Math.round(visitsPerSecond*3600);root.innerHTML='<section class="campaign-start"><div><p class="kicker">PAYMENT CONFIRMED</p><h1>Your campaign is delivering.</h1><p>Your verified campaign is live. Delivery is paced across your selected '+safe(campaign.delivery||deliveryHours+' hours')+' window, and activity updates below as visitors arrive.</p></div><span class="campaign-status"><i></i> Delivering now<br><b>'+hourlyRate.toLocaleString()+'/hour</b></span></section><section class="activity-head"><div><p class="kicker">LIVE CAMPAIGN</p><h2>'+safe(campaign.plan)+' campaign activity</h2></div><span>'+safe(campaign.visitors.toLocaleString())+' visitors · '+deliveryHours+'h delivery</span></section><section class="activity-layout"><div class="activity-metric"><span>Page visits</span><b id="visits">0</b><small>Live total</small></div><div class="activity-metric"><span>Unique visitors</span><b id="unique">0</b><small>Live total</small></div><div class="recent-feed"><div class="section-heading"><h2>Recent page visits</h2><span>Updates automatically</span></div><div id="visit-rows" class="vertical-visits"></div></div></section>';
const elapsed=Math.max(0,(Date.now()-campaign.startedAt)/1000),initial=Math.min(campaign.visitors,Math.max(1,Math.floor(elapsed*visitsPerSecond)));let visits=initial,unique=Math.max(1,Math.round(initial*.405)),browsers=['Facebook for Android','OppoBrowser','Chrome Mobile','Firefox','Safari Mobile'];const visitsEl=document.getElementById('visits'),uniqueEl=document.getElementById('unique'),rows=document.getElementById('visit-rows'),tickMs=850;const row=index=>`<article class="visit-feed-row">${countryFlag()}<span class="feed-device">${deviceIcon(index%4?'phone':'desktop')}</span><div><b>${browsers[index%browsers.length]}</b><small>${safe(campaign.url)}</small></div><time>Just now</time></article>`;const renderMetrics=()=>{visitsEl.textContent=visits.toLocaleString();uniqueEl.textContent=unique.toLocaleString()};renderMetrics();rows.innerHTML=Array.from({length:6},(_,index)=>row(index)).join('');setInterval(()=>{if(visits>=campaign.visitors)return;const variation=.93+Math.random()*.14,increment=Math.max(1,Math.round(visitsPerSecond*(tickMs/1000)*variation));visits=Math.min(campaign.visitors,visits+increment);unique=Math.max(unique,Math.round(visits*.405));renderMetrics();visitsEl.classList.add('metric-pulse');uniqueEl.classList.add('metric-pulse');setTimeout(()=>{visitsEl.classList.remove('metric-pulse');uniqueEl.classList.remove('metric-pulse')},420);rows.insertAdjacentHTML('afterbegin',row(Math.floor(Math.random()*5)));rows.lastElementChild.remove()},tickMs)}
monitorVerification();
